### ISSUE TITLE
Upgrade Bower

### ISSUE THREAD

**Issue by treshugart** [chrisgladd/grunt-phantomcss#31]
It seems the version of Bower [you're depending on](https://github.com/chrisgladd/grunt-phantomcss/blob/master/package.json#L42) [depends on a version](https://github.com/bower/bower/blob/v1.0.3/package.json#L24) of `bower-config` that [doesn't exist anymore](https://github.com/bower/config/tree/0.2.0). The earliest version of `bower-config` that exists is 0.3.0. I'm not sure why this just started happening, but it's breaking `npm` installs for us and probably many other people.

List of GitHub tags:

![screen shot 2014-10-14 at 4 51 26 pm](https://cloud.githubusercontent.com/assets/136556/4624555/56c64dc8-5366-11e4-9a61-fe470aba93cb.png)

List of NPM versions:

![screen shot 2014-10-14 at 4 53 52 pm](https://cloud.githubusercontent.com/assets/136556/4624565/8eb72c66-5366-11e4-9692-e02f846b15be.png)

**Comment by ChrisBAshton** [comment]
+1

**Comment by AlfonsoFilho** [comment]
+1

**Comment by diegoeis** [comment]
+1
This happening when I trying to install grunt-phantomcss module.

**Comment by elbowz** [comment]
+1

Any workaround?

**Comment by mstrutt** [comment]
@elbowz there's a pull request open that fixes this, you can install it directly for now: `npm install clarkeadg/grunt-phantomcss --save-dev`

**Comment by elbowz** [comment]
great thanks!

**Comment by Fowowski** [comment]
+1

Any news on this?

**Comment by martinkr** [comment]
+1

**Comment by MarioAraque** [comment]
+1

**Comment by schorfES** [comment]
+ 1

**Comment by lukefrake** [comment]
:+1:

**Comment by brunowego** [comment]
+1

**Comment by majora2007** [comment]
+1

**Comment by lejeunerenard** [comment]
:+1:

**Comment by fassetar** [comment]
+1

**Comment by tommysanterre** [comment]
+1

**Comment by qikkeronline** [comment]
+1

**Comment by chrisgladd** [comment]
Fixed in v0.3.0
