### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by Violo** [chrisgladd/grunt-phantomcss#35]
I'm getting the following error when trying to install

npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/Users/alessandro/.nvm/v0.10.28/bin/npm" "install" "grunt-phantomcss" "--save-dev"
npm ERR! node v0.10.28
npm ERR! npm  v2.1.6
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: bower-config@'>=0.2.0 <0.3.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.1.0-rc.1","0.1.0-rc.2","0.1.0-rc.3","0.1.0-rc.4","0.1.0-rc.5","0.2.0-rc.1","0.2.0-rc.2","0.3.0","0.3.1","0.3.3","0.3.4","0.3.5","0.4.0","0.4.1","0.4.2","0.4.3","0.4.4","0.4.5","0.5.0","0.5.1","0.5.2"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by ChrisBAshton** [comment]
I'm getting the same error!
