### ISSUE TITLE
Cannot define property:33, object is not extensible

### ISSUE THREAD

**Issue by Fowowski** [chrisgladd/grunt-phantomcss#41]
Hello,

I'm using windows 7, after cloning this repo and applying this patch https://github.com/chrisgladd/grunt-phantomcss/pull/36 the install process went well although calling default grunt task phantomcss:visualTest returns:

Warning: cannot define property:33, object is not extensible. Use --force to continue.

Aborted due to warnings.

My npm and node versions:
npm -v
2.5.1

node -v
v0.12.0

Thanks in advance!

**Comment by chrisgladd** [comment]
Fixed in v0.3.0
