### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by ArmorDarks** [chrisgladd/grunt-phantomcss#45]
This repository seems to be not maintained anymore.

Are there any actively developed forks?

Thanks in advance!

**Comment by EmilioAiolfi** [comment]
@ArmorDarks exists other updated repository, created for @micahgodbolt.

https://github.com/micahgodbolt/grunt-phantomcss

**Comment by micahgodbolt** [comment]
Yup! I'm keeping this maintained. I've made some modifications to some of the logic, but we're using it on several projects and it works well.

**Comment by brunowego** [comment]
Thanks @EmilioAiolfi :+1:

**Comment by jcrben** [comment]
Seems like a lot of libraries that I encounter these days are dead. Twitter's typeahead.js (https://github.com/twitter/typeahead.js) is also abandoned and a group is working on a fork (https://github.com/corejavascript/typeahead.js) - I got invited as a collaborator.

It would be nice if we could gather these abandoned projects under an organization or organizations, which could hopefully also enforce semantic versioning.

**Comment by ArmorDarks** [comment]
Before making tons of forks it's better to try reach original developer. Most part of devs happily transferring repositories to someone else for maintenance

**Comment by micahgodbolt** [comment]
Welcome back @chrisgladd!
